export * from "./getNumberOfChar"
export * from "./getNumberOfSpaces"
export * from "./getNumberOfWords"
export * from "./getNumberOfSentences"
export * from "./getNumberOfPunctuations"
export * from "./getNumberOfParagraphs"